# This is a basic workflow to run in OpenFOAM v2206 containers
name: OF2206

# Make sure shells are interactive, so OF can get sourced
defaults:
  run:
    shell: bash -o pipefail -i {0}

# Controls when the workflow will run
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/foamscience/jammy-openfoam:v2206
      options: --cpus 2 --user openfoam
      env:
        CATCH_TIMEOUT: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Compile and Test
        run: |
          source /usr/lib/openfoam/openfoam2206/etc/bashrc
          git clone https://github.com/FoamScience/OpenFOAM-Unit-testing --branch=of2206 ut
          rm -rf ut/tests/serialParallelTests ut/tests/Make
          ln -s "$PWD/serialParallelTests" "$PWD/ut/tests/serialParallelTests"
          ln -s "$PWD/Make" "$PWD/ut/tests/Make"
          ls ut/tests/Make ut/tests/serialParallelTests
          cd ut
          sed -i 's/mpirun/mpirun --oversubscribe/g' Alltest
          ./Alltest
